"""
A generic setup.py file generated by django duke client %(duke_client_version)s
"""

from setuptools import setup, find_packages

setup(
    name = "%(project_name)s",
    version = "0.0.1",
    url = "",
    license = "",
    description = "",
    author = '',
    packages = find_packages('eggs'),
    package_dir = {'': '.'},
    install_requires = [],
)
