#!/usr/bin/env bash
python setup.py test
#export NOSE_WITH_COVERAGE=true
#coverage run setup.py test
#coverage report --rcfile=tests/.coveragerc -m dukeclient/*.py dukeclient/commands/*.py
#coverage debug --rcfile=tests/.coveragerc data
